<<<<<<< HEAD
<p>Error on Apr 13, 2015 14:56PM - preg_replace():  in /opt/lampp/htdocs/seminario_mvc/app/helpers/url.php on line 71</p><h3>Exception information:</h3>
=======
<p>Error on Apr 13, 2015 18:24PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:23PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:23PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:21PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:14PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:14PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:13PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:13PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:13PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:12PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 18:09PM - PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php on line 54</p><p>Error on Apr 13, 2015 14:56PM - preg_replace():  in /opt/lampp/htdocs/seminario_mvc/app/helpers/url.php on line 71</p><h3>Exception information:</h3>
>>>>>>> 60d6dc3c5e4cc6085486def6fac974a95cd25f20

		<p><strong>Date:</strong> Apr 13, 2015 13:02PM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1049] Unknown database 'seminario'</p>

		<p><strong>Code:</strong> 1049</p>

		<p><strong>File:</strong> /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php(54): PDO->__construct('mysql:host=loca...', 'root', '')
#1 /opt/lampp/htdocs/seminario_mvc/app/core/model.php(25): helpers\Database::get()
#2 /opt/lampp/htdocs/seminario_mvc/app/controllers/seminario.php(10): core\Model->__construct()
#3 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(80): controllers\Seminario->__construct(NULL)
#4 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(179): core\Router::invokeObject('\\controllers\\se...')
#5 /opt/lampp/htdocs/seminario_mvc/index.php(109): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Apr 13, 2015 13:02PM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1049] Unknown database 'seminario'</p>

		<p><strong>Code:</strong> 1049</p>

		<p><strong>File:</strong> /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php(54): PDO->__construct('mysql:host=loca...', 'root', '')
#1 /opt/lampp/htdocs/seminario_mvc/app/core/model.php(25): helpers\Database::get()
#2 /opt/lampp/htdocs/seminario_mvc/app/controllers/seminario.php(10): core\Model->__construct()
#3 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(80): controllers\Seminario->__construct(NULL)
#4 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(179): core\Router::invokeObject('\\controllers\\se...')
#5 /opt/lampp/htdocs/seminario_mvc/index.php(109): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<p>Error on Apr 13, 2015 12:59PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/seminario_mvc/app/helpers/session.php on line 24</p><h3>Exception information:</h3>

		<p><strong>Date:</strong> Apr 12, 2015 23:36PM</p>

		<p><strong>Message:</strong> Invalid cell coordinate AARRAY</p>

		<p><strong>Code:</strong> 0</p>

		<p><strong>File:</strong> /opt/lampp/htdocs/seminario_mvc/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php</p>

		<p><strong>Line:</strong> 590</p>

		<h3>Stack trace:</h3>

		<pre>#0 /opt/lampp/htdocs/seminario_mvc/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php(1227): PHPExcel_Cell::coordinateFromString('AARRAY')
#1 /opt/lampp/htdocs/seminario_mvc/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php(1186): PHPExcel_Worksheet->_createNewCell('AARRAY')
#2 /opt/lampp/htdocs/seminario_mvc/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php(1095): PHPExcel_Worksheet->getCell('AArray')
#3 /opt/lampp/htdocs/seminario_mvc/app/helpers/exportexcel.php(24): PHPExcel_Worksheet->setCellValue('AArray', NULL)
#4 /opt/lampp/htdocs/seminario_mvc/app/controllers/admin/asistentes.php(165): helpers\ExportExcel::export(Array)
#5 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(85): controllers\admin\Asistentes->export()
#6 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(179): core\Router::invokeObject('\\controllers\\ad...')
#7 /opt/lampp/htdocs/seminario_mvc/index.php(109): core\Router::dispatch()
#8 {main}</pre>

		<hr />
<p>Error on Apr 12, 2015 23:32PM - mysqli_fetch_object() expects parameter 1 to be mysqli_result, null given in /opt/lampp/htdocs/seminario_mvc/app/helpers/exportexcel.php on line 22</p><p>Error on Apr 12, 2015 22:54PM - require(PHPExcel/PHPExcel.php): failed to open stream: No such file or directory in /opt/lampp/htdocs/seminario_mvc/app/helpers/exportexcel.php on line 2</p><h3>Exception information:</h3>

		<p><strong>Date:</strong> Apr 12, 2015 2:58AM</p>

		<p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sistenteID' in 'where clause'</p>

		<p><strong>Code:</strong> 42S22</p>

		<p><strong>File:</strong> /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php</p>

		<p><strong>Line:</strong> 195</p>

		<h3>Stack trace:</h3>

		<pre>#0 /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php(195): PDOStatement->execute()
#1 /opt/lampp/htdocs/seminario_mvc/app/models/admin/asistentes.php(22): helpers\Database->delete('sm_asistentes', Array)
#2 /opt/lampp/htdocs/seminario_mvc/app/controllers/admin/asistentes.php(152): models\admin\Asistentes->deleteAsistente(Array)
#3 [internal function]: controllers\admin\Asistentes->delete('4')
#4 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(90): call_user_func_array(Array, Array)
#5 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(219): core\Router::invokeObject('\\controllers\\ad...', Array)
#6 /opt/lampp/htdocs/seminario_mvc/index.php(108): core\Router::dispatch()
#7 {main}</pre>

		<hr />
<p>Error on Apr 12, 2015 2:34AM - Invalid argument supplied for foreach() in /opt/lampp/htdocs/seminario_mvc/app/views/admin/asistentes.php on line 40</p><h3>Exception information:</h3>

		<p><strong>Date:</strong> Apr 11, 2015 1:13AM</p>

		<p><strong>Message:</strong> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ponenteCentro' in 'field list'</p>

		<p><strong>Code:</strong> 42S22</p>

		<p><strong>File:</strong> /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php</p>

		<p><strong>Line:</strong> 114</p>

		<h3>Stack trace:</h3>

		<pre>#0 /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php(114): PDOStatement->execute()
#1 /opt/lampp/htdocs/seminario_mvc/app/models/admin/ponentes.php(14): helpers\Database->insert('sm_ponentes', Array)
#2 /opt/lampp/htdocs/seminario_mvc/app/controllers/admin/ponentes.php(54): models\admin\Ponentes->insertPonente(Array)
#3 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(85): controllers\admin\Ponentes->add()
#4 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(179): core\Router::invokeObject('\\controllers\\ad...')
#5 /opt/lampp/htdocs/seminario_mvc/index.php(91): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<h3>Exception information:</h3>

		<p><strong>Date:</strong> Apr 11, 2015 0:53AM</p>

		<p><strong>Message:</strong> SQLSTATE[HY000] [1049] Unknown database 'seminario'</p>

		<p><strong>Code:</strong> 1049</p>

		<p><strong>File:</strong> /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php</p>

		<p><strong>Line:</strong> 54</p>

		<h3>Stack trace:</h3>

		<pre>#0 /opt/lampp/htdocs/seminario_mvc/app/helpers/database.php(54): PDO->__construct('mysql:host=loca...', 'root', '')
#1 /opt/lampp/htdocs/seminario_mvc/app/core/model.php(25): helpers\Database::get()
#2 /opt/lampp/htdocs/seminario_mvc/app/controllers/seminario.php(10): core\Model->__construct()
#3 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(80): controllers\Seminario->__construct(NULL)
#4 /opt/lampp/htdocs/seminario_mvc/app/core/router.php(179): core\Router::invokeObject('\\controllers\\se...')
#5 /opt/lampp/htdocs/seminario_mvc/index.php(91): core\Router::dispatch()
#6 {main}</pre>

		<hr />
<p>Error on Apr 08, 2015 15:37PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:37PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:36PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:36PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:36PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:36PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:36PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:35PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:35PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:35PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:31PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:31PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:29PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:29PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:29PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:26PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:26PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:26PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:26PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p><p>Error on Apr 08, 2015 15:25PM - session_start(): open(/opt/lampp/temp//sess_qb8218eoskup5qlcvqs34am0l0, O_RDWR) failed: Permission denied (13) in /opt/lampp/htdocs/v2/app/helpers/session.php on line 24</p>